arb-dir: lib/l10n
template-arb-file: app_en.arb
output-dir: lib/gen_l10n
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: lib/l10n/untranslated.txt
preferred-supported-locales:
  - en
  - hi
  - mr
  - ur
  - ta
  - te
  - gu
  - bn
  - pa
  - kn
  - ja
  - fr
  - es
  - de
