name: silvra_vpn
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.2.1
  google_fonts: ^4.0.3
  url_launcher: ^6.2.6
  shared_preferences: ^2.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen: any

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/world_map.png
    # Agar tum aur images ya icons add karoge to yaha add karna
    # - assets/icons/
    # - assets/flags/

# Flutter Intl plugin / l10n config
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/gen_l10n
